--- # Operation
interface: operation.html

hardware:
  - vendorID: 1003
    deviceID: 8256

configuration:
  timeout:
    description:  "Time allowed to complete the Operation."
    default:      28

metrics:
  elapsed_time:
    description:    "Time taken to complete the Operation; minimum value to prevent cheating."
    values:
      - units:      Seconds
        threshold:  maximum
        default:    12

      - units:      Seconds
        threshold:  minimum
        default:    3

  errors:
    description:    "Number and length of errors allowed."
    values:
      - units:      Count
        threshold:  maximum
        default:    2

      - units:      Total milliseconds
        threshold:  maximum
        default:    500